"""Add subType to user model, remove subType from customer model, remove premium from user model

Revision ID: b99c9a9c7671
Revises: 40ac2c7ea0d9
Create Date: 2021-04-08 10:43:39.799299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99c9a9c7671'
down_revision = '40ac2c7ea0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'subType')
    op.add_column('users', sa.Column('subType', sa.Integer(), nullable=True))
    op.drop_column('users', 'premium')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('premium', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'subType')
    op.add_column('customers', sa.Column('subType', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
