"""Add brand, last4, expMonth, expYear on to Customer.

Revision ID: b6fdbae272eb
Revises: f3494c0f20b8
Create Date: 2021-04-03 19:56:37.384650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6fdbae272eb'
down_revision = 'f3494c0f20b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('brand', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('expMonth', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('expYear', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('last4', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'customers', ['userId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'last4')
    op.drop_column('customers', 'expYear')
    op.drop_column('customers', 'expMonth')
    op.drop_column('customers', 'brand')
    # ### end Alembic commands ###
