"""Add premium to users, remove timeSent from tests

Revision ID: d7cdfbd360a8
Revises: 42bcbc6f68c9
Create Date: 2021-03-25 15:11:18.845575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7cdfbd360a8'
down_revision = '42bcbc6f68c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'timeSent')
    op.add_column('users', sa.Column('premium', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'premium')
    op.add_column('tests', sa.Column('timeSent', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
