"""Add customer model.

Revision ID: f3494c0f20b8
Revises: d7cdfbd360a8
Create Date: 2021-03-31 17:11:05.307584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3494c0f20b8'
down_revision = 'd7cdfbd360a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('stripeCustomerId', sa.String(length=255), nullable=False),
    sa.Column('stripeSubscriptionId', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripeCustomerId'),
    sa.UniqueConstraint('stripeSubscriptionId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
