"""Remove unique constraint from client code

Revision ID: de98f7f64bfc
Revises: 95c9416a168d
Create Date: 2021-04-13 17:44:53.093663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de98f7f64bfc'
down_revision = '95c9416a168d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_code_key', 'clients', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('clients_code_key', 'clients', ['code'])
    # ### end Alembic commands ###
