"""Add lastBillDate and subStatus to customer model

Revision ID: aef9db629d9d
Revises: de98f7f64bfc
Create Date: 2021-06-14 18:58:15.663995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef9db629d9d'
down_revision = 'de98f7f64bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('lastBillDate', sa.DateTime(), nullable=True))
    op.add_column('customers', sa.Column('subStatus', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'subStatus')
    op.drop_column('customers', 'lastBillDate')
    # ### end Alembic commands ###
