"""Add uniqure onto client code

Revision ID: 63f3d99c4fda
Revises: fb9f9381f7d8
Create Date: 2021-03-08 11:28:10.290296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f3d99c4fda'
down_revision = 'fb9f9381f7d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'clients', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    # ### end Alembic commands ###
