"""Add nextBillDate to customer model

Revision ID: 95c9416a168d
Revises: b99c9a9c7671
Create Date: 2021-04-09 13:55:57.571245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c9416a168d'
down_revision = 'b99c9a9c7671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('nextBillDate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'nextBillDate')
    # ### end Alembic commands ###
