"""Update users table

Revision ID: 7dc41674d36a
Revises: b8e5b70a70f4
Create Date: 2021-03-04 14:53:21.118627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc41674d36a'
down_revision = 'b8e5b70a70f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lic', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('pxName', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pxName')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'lic')
    # ### end Alembic commands ###
